name: wss_chat
description: Client of a wss chat
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  google_fonts: ^3.0.1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dio: ^4.0.6
  flutter_svg: ^1.1.1+1
  shimmer: ^2.0.0
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  fonts:
    - family: Object Sans
      fonts:
        - asset: assets/fonts/os_reg.ttf
  assets:
    - assets/logo_icon.svg
    - assets/logo.png


  uses-material-design: true
  generate: true #

